"""AUTO-GENERATED by generate_frozen_reference.py --overwrite (2026-09-21T01:41:12Z).

Frozen, fully expanded cobaya configuration for emul2_example2
(source: EXAMPLE_EMUL2_EVALUATE2.yaml resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {
    "As_1e9": 2.1,
    "H0": 67.32,
    "LSST_A1_1": 0.606102,
    "LSST_A1_2": -1.51541,
    "LSST_A2_1": 0.0,
    "LSST_A2_2": -1.51541,
    "LSST_B1_1": 1.72716,
    "LSST_B1_2": 1.65168,
    "LSST_B1_3": 1.61423,
    "LSST_B1_4": 1.92886,
    "LSST_B1_5": 2.11633,
    "LSST_BTA_1": 0.0,
    "LSST_DZ_L1": 0.00457604,
    "LSST_DZ_L2": 0.000309875,
    "LSST_DZ_L3": 0.00855907,
    "LSST_DZ_L4": -0.00316269,
    "LSST_DZ_L5": -0.0146753,
    "LSST_DZ_S1": 0.0414632,
    "LSST_DZ_S2": 0.00147332,
    "LSST_DZ_S3": 0.0237035,
    "LSST_DZ_S4": -0.0773436,
    "LSST_DZ_S5": -8.67127e-05,
    "LSST_M1": 0.0191832,
    "LSST_M2": -0.0431752,
    "LSST_M3": -0.034961,
    "LSST_M4": -0.0158096,
    "LSST_M5": -0.0158096,
    "ns": 0.96605,
    "omegab": 0.04,
    "omegam": 0.3,
    "w": -0.9,
    "w0pwa": -0.9
}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.65
    proposal: 0.4
    latex: 10^9 A_\mathrm{s}
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 5
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.004
    proposal: 0.004
    latex: \Omega_\mathrm{b}
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}
  w0pwa:
    prior:
      min: -5
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    derived: false
    latex: w_{a,\mathrm{DE}}
  LSST_A2_1:
    latex: A_\mathrm{2-IA,LSST}^1
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.36
      scale: 0.5
    proposal: 0.5
  LSST_A2_2:
    latex: A_\mathrm{2-IA,LSST}^2
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -2.5
      scale: 0.5
    proposal: 0.5
  LSST_BTA_1:
    latex: A_\mathrm{BTA-IA,LSST}^1
    prior:
      min: 0
      max: 2
    ref:
      dist: norm
      loc: 1
      scale: 0.15
    proposal: 0.1
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
    derived: true
  mnu:
    value: 0.06
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
    derived: true
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
    derived: true
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  LSST_BMAG_1:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^1
  LSST_BMAG_2:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^2
  LSST_BMAG_3:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^3
  LSST_BMAG_4:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^4
  LSST_BMAG_5:
    value: 0.0
    latex: b_\mathrm{BMAG-LSST}^5
  LSST_DZ_L1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^1
  LSST_DZ_L2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^2
  LSST_DZ_L3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^3
  LSST_DZ_L4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^4
  LSST_DZ_L5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^5
  LSST_B1_1:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.24
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-LSST}^1
  LSST_B1_2:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.36
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-LSST}^2
  LSST_B1_3:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.47
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-LSST}^3
  LSST_B1_4:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.6
      scale: 0.15
    proposal: 0.1
    latex: b_\mathrm{1-LSST}^4
  LSST_B1_5:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.76
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-LSST}^5
  LSST_B2_1:
    value: 0.0
    latex: b_\mathrm{2-LSST}^1
  LSST_B2_2:
    value: 0.0
    latex: b_\mathrm{2-LSST}^2
  LSST_B2_3:
    value: 0.0
    latex: b_\mathrm{2-LSST}^3
  LSST_B2_4:
    value: 0.0
    latex: b_\mathrm{2-LSST}^4
  LSST_B2_5:
    value: 0.0
    latex: b_\mathrm{2-LSST}^5
  LSST_B3NL_1:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^1
  LSST_B3NL_2:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^2
  LSST_B3NL_3:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^3
  LSST_B3NL_4:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^4
  LSST_B3NL_5:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^5
  LSST_BK_1:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^1
  LSST_BK_2:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^2
  LSST_BK_3:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^3
  LSST_BK_4:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^4
  LSST_BK_5:
    value: 0.0
    latex: b_\mathrm{B3NL-LSST}^5
  LSST_PM1:
    value: 0.0
    latex: PM_\mathrm{LSST}^1
  LSST_PM2:
    value: 0.0
    latex: PM_\mathrm{LSST}^2
  LSST_PM3:
    value: 0.0
    latex: PM_\mathrm{LSST}^3
  LSST_PM4:
    value: 0.0
    latex: PM_\mathrm{LSST}^4
  LSST_PM5:
    value: 0.0
    latex: PM_\mathrm{LSST}^5
  LSST_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^1
  LSST_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^2
  LSST_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^3
  LSST_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^4
  LSST_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^5
  LSST_A1_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.7
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^1
  LSST_A1_2:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.7
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^2
  LSST_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^3
  LSST_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^4
  LSST_A1_5:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^5
  LSST_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^3
  LSST_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^4
  LSST_A2_5:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^5
  LSST_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^2
  LSST_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^3
  LSST_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^4
  LSST_BTA_5:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^5
  LSST_M1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{LSST}^1
  LSST_M2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{LSST}^2
  LSST_M3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{LSST}^3
  LSST_M4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{LSST}^4
  LSST_M5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: m_\mathrm{LSST}^5
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  LSST_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{LSST}^3
  LSST_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{LSST}^4
likelihood:
  lsst_y1.combo_3x2pt:
    path: ./projects/lsst_y1/tests/frozen/data
    data_file: lsst_y1_M1_GGL0.05.dataset
    accuracyboost: 1.0
    integration_accuracy: 0
    lmax: 50000
    kmax_boltzmann: 5.0
    speed: 1
    non_linear_emul: 2
    external_nz_modeling: 0
    use_emulator: 2
    debug: false
    IA_redshift_evolution: 3
    IA_model: 0
    IA_code: 0
    bias_model:
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    add_baryons_on_dv: false
    which_bsims_add_on_dv: antilles-2
    use_baryon_pca: false
    create_baryon_pca: false
    baryon_pca_select_sims: antilles-2-99/antilles-101-378/antilles-380-400
    filename_baryon_pca: ./projects/lsst_y1/chains/pca.txt
    external_baryon_suppression: false
    print_datavector: false
    print_datavector_file: ./projects/lsst_y1/chains/theory.modelvector
    type: []
    stop_at_error: false
    version: null
    input_params:
    - H0
    - omegam
    - LSST_A2_1
    - LSST_A2_2
    - LSST_BTA_1
    - As
    - LSST_BMAG_1
    - LSST_BMAG_2
    - LSST_BMAG_3
    - LSST_BMAG_4
    - LSST_BMAG_5
    - LSST_DZ_L1
    - LSST_DZ_L2
    - LSST_DZ_L3
    - LSST_DZ_L4
    - LSST_DZ_L5
    - LSST_B1_1
    - LSST_B1_2
    - LSST_B1_3
    - LSST_B1_4
    - LSST_B1_5
    - LSST_B2_1
    - LSST_B2_2
    - LSST_B2_3
    - LSST_B2_4
    - LSST_B2_5
    - LSST_B3NL_1
    - LSST_B3NL_2
    - LSST_B3NL_3
    - LSST_B3NL_4
    - LSST_B3NL_5
    - LSST_BK_1
    - LSST_BK_2
    - LSST_BK_3
    - LSST_BK_4
    - LSST_BK_5
    - LSST_PM1
    - LSST_PM2
    - LSST_PM3
    - LSST_PM4
    - LSST_PM5
    - LSST_DZ_S1
    - LSST_DZ_S2
    - LSST_DZ_S3
    - LSST_DZ_S4
    - LSST_DZ_S5
    - LSST_A1_1
    - LSST_A1_2
    - LSST_A1_3
    - LSST_A1_4
    - LSST_A1_5
    - LSST_A2_3
    - LSST_A2_4
    - LSST_A2_5
    - LSST_BTA_2
    - LSST_BTA_3
    - LSST_BTA_4
    - LSST_BTA_5
    - LSST_M1
    - LSST_M2
    - LSST_M3
    - LSST_M4
    - LSST_M5
    - LSST_BARYON_Q1
    - LSST_BARYON_Q2
    - LSST_BARYON_Q3
    - LSST_BARYON_Q4
    output_params: []
theory:
  emulrdrag:
    renames: null
    extra_args:
      file:
      - external_modules/data/emultrf/BAO_SN_RES/emul_lcdm_rdrag_GP.joblib
      extra:
      - external_modules/data/emultrf/BAO_SN_RES/extra_lcdm_rdrag.npy
      ord:
      - - omegabh2
        - omegach2
    speed: -1
    stop_at_error: false
    version: null
    path: ./cobaya/cobaya/theories/
    provides:
    - rdrag
    input_params:
    - omegabh2
    - omegach2
    output_params:
    - rdrag
  emulbaosn:
    renames: null
    extra_args:
      device: cpu
      file:
      - None
      - external_modules/data/emultrf/BAO_SN_RES/w0wa/emul_w0wa_H.pt
      extra:
      - None
      - external_modules/data/emultrf/BAO_SN_RES/w0wa/extra_w0wa_H.npy
      ord:
      - None
      - - omegam
        - H0
        - w
        - wa
      extrapar:
      - MLA: INT
        ZMIN: 0.0001
        ZMAX: 3
        NZ: 600
      - MLA: ResMLP
        offset: 0.0
        INTDIM: 4
        NLAYER: 6
        TMAT: external_modules/data/emultrf/BAO_SN_RES/w0wa/PCA_w0wa_H.npy
        ZLIN: external_modules/data/emultrf/BAO_SN_RES/w0wa/z_lin_w0wa.npy
    speed: -1
    stop_at_error: true
    version: null
    path: ./cobaya/cobaya/theories/
    provides:
    - comoving_radial_distance
    - angular_diameter_distance
    - Hubble
    input_params:
    - H0
    - omegam
    - w
    - wa
    output_params: []
  emulmps:
    speed: -1
    stop_at_error: true
    version: 1.0.0
    path: ./cobaya/cobaya/theories/
    extra_args:
      model_file: external_modules/data/emultrf/emulmps/npce_emul/emulator_npce.keras
      metadata_file: external_modules/data/emultrf/emulmps/npce_emul/metadata.joblib
      nl_model_file: external_modules/data/emultrf/emulmps/w0wa_halofit/emulator_halofit.keras
      nl_metadata_file: external_modules/data/emultrf/emulmps/w0wa_halofit/metadata.joblib
      use_syren: false
      param_order:
      - As_1e9
      - ns
      - H0
      - omegab
      - omegam
      - w
      - wa
    input_params:
    - As_1e9
    - ns
    - H0
    - omegab
    - omegam
    - w
    - wa
    output_params: []
timing: false
"""
