"""Maintainer tool: (re)create the frozen state the unit tests run on.

Running this REDEFINES what the tests protect, so it refuses to run
without the explicit --overwrite flag. Only run it when a change to
the data vectors, n(z), covariance, examples, or likelihood defaults
is deliberate, and review the printed chi2 values before committing:
they become the new references the tests compare against.

What one run produces, all under tests/ (see cocoa_test_utils for how
the tests consume each piece):

  - frozen/data/: a copy of the CURRENT ../data folder.
  - frozen/EXAMPLE_EVALUATE{1,2}.yaml: snapshots of the current
    examples, kept for humans to diff (the tests never load them).
  - frozen/frozen_config_*.py: for each configuration listed in
    cocoa_test_utils.EXAMPLES, the model is built from the CURRENT
    example yaml, cobaya resolves it against the CURRENT likelihood
    defaults, and the complete resolved configuration is written back
    out as a yaml string, together with the exact evaluation point.
    Writing out every resolved option and parameter is what makes the
    tests independent of later edits to the live files. The 2x2pt
    entry starts from example2 with the likelihood block renamed; the
    EMUL2 entries carry the emulator theory stack with the network
    device forced to "cpu" (deterministic and machine-independent; the
    trained network files themselves are NOT copied: they live in
    external_modules/data/emultrf and are pinned by the EMULTRF keys
    in set_installation_options.sh).
  - frozen/reference_chi2.json: the reference chi2 values, one per
    configuration and variant (NLA for all; TATT for the exact
    configurations; TATT with python FAST-PT for example1/2, plus the
    saved FASTPT-minus-CFASTPT difference), computed FROM the frozen
    modules just written, exactly the way the tests will compute them.
  - manifest_sha256.json: the SHA-256 pin of every frozen file.

Usage (from the Cocoa/ folder, cocoa environment active,
start_cocoa.sh sourced):

    python ./projects/lsst_y1/tests/generate_frozen_reference.py --overwrite
"""

import json
import os
import shutil
import sys
import time

# The references must be produced under the same OpenMP thread count
# the tests enforce, and before any cobaya/cosmolike import.
os.environ["OMP_NUM_THREADS"] = "4"

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cocoa_test_utils as u

PROJECT_DIR = os.path.dirname(u.TESTS_DIR)

# Stored inside the frozen configurations as the likelihood data path.
# ROOTDIR-relative on purpose: the frozen modules stay portable across
# machines, and the tests overwrite it with the absolute path anyway.
FROZEN_DATA_RELPATH = "./projects/lsst_y1/tests/frozen/data"

# The skeleton of one generated frozen-configuration module. The yaml
# goes inside r""" so latex backslashes in parameter labels survive.
MODULE_TEMPLATE = '''\
"""AUTO-GENERATED by generate_frozen_reference.py --overwrite ({stamp}).

Frozen, fully expanded cobaya configuration for {example}
(source: {source} resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {point}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
{yaml}
"""
'''


def freeze_example(example, stamp):
    """Write one example's fully expanded frozen-configuration module.

    The expansion works by round trip through cobaya: build the model
    from the live example yaml (letting cobaya merge in the live
    likelihood defaults), then ask the model for its resolved
    configuration with model.info() and store THAT. The resolved form
    lists every option and every parameter explicitly, so the frozen
    module no longer depends on any live default.

    Arguments:
      example = "example1" or "example2" (a key of u.EXAMPLES).
      stamp   = the UTC time string written into the module header.

    Returns:
      nothing; frozen/frozen_config_<example>.py is written.

    Raises:
      ValueError when a sampled parameter is neither overridden by the
      example's evaluate block nor given a ref center to fall back on
      (the point would be undefined at that parameter).
    """
    from cobaya.yaml import yaml_load_file, yaml_dump

    cfg = u.EXAMPLES[example]
    live = yaml_load_file(os.path.join(PROJECT_DIR, cfg["provenance"]))
    # The evaluate sampler's override block is the example's fiducial
    # point; keep it before stripping the sampler from the info.
    override = dict(live["sampler"]["evaluate"]["override"])
    live.pop("sampler", None)
    live.pop("output", None)
    live["debug"] = 30
    live["timing"] = False
    # the 2x2pt configuration reuses example2's yaml with the
    # likelihood renamed (combo_3x2pt -> combo_2x2pt: same options,
    # same data, different probe selection inside cosmolike)
    source_name = cfg.get("source_likelihood", cfg["likelihood"])
    likelihood_block = live["likelihood"].pop(source_name)
    live["likelihood"][cfg["likelihood"]] = likelihood_block
    likelihood_block["path"] = FROZEN_DATA_RELPATH
    likelihood_block["IA_model"] = 0
    if cfg.get("emulator"):
        # the emulated BAO/SN network declares device "cuda" in the
        # example; freezing "cpu" keeps the reference reproducible on
        # machines without a CUDA GPU (and torch on cpu is
        # deterministic)
        live["theory"]["emulbaosn"]["extra_args"]["device"] = "cpu"

    # make_model builds the evaluable cobaya Model; building it is
    # what forces cobaya to merge the live likelihood defaults into
    # the configuration
    model = u.make_model(live)
    # model.info() returns the configuration with every default
    # resolved: the complete likelihood option set and the complete
    # parameter list, exactly what must be frozen.
    updated = model.info()
    updated.pop("output", None)
    updated.pop("packages_path", None)
    updated["likelihood"][cfg["likelihood"]]["path"] = FROZEN_DATA_RELPATH

    # The frozen point: the example's override where given, the ref
    # center otherwise. Fallbacks are printed so the maintainer can
    # confirm each one is intended.
    point = {}
    fallback = []
    for name in model.parameterization.sampled_params():
        if name in override:
            point[name] = override[name]
        else:
            ref = updated["params"][name].get("ref")
            point[name] = ref["loc"] if isinstance(ref, dict) else ref
            fallback.append(name)
            if point[name] is None:
                raise ValueError(
                    f"parameter {name}: not in override and no ref")
    if fallback:
        print(f"{example}: point uses ref centers for {fallback}", flush=True)

    with open(os.path.join(u.FROZEN_DIR, cfg["frozen_module"]), "w") as f:
        f.write(MODULE_TEMPLATE.format(
            stamp=stamp,
            example=example,
            source=cfg["provenance"],
            point=json.dumps(point, indent=4, sort_keys=True),
            yaml=yaml_dump(updated).rstrip("\n"),
        ))
    print(f"{example}: frozen config expanded to "
          f"{len(updated['params'])} parameters "
          f"({len(live['params'])} in the live example yaml)", flush=True)


def main():
    """Rebuild tests/frozen/ and the manifest from the current project.

    The steps, in order: refuse without --overwrite; delete and
    recreate frozen/; copy the data and the example snapshots; write
    the two expanded frozen-configuration modules; evaluate the four
    reference chi2 values from those modules (the same code path the
    tests use); write the reference file; hash everything into the
    manifest. The manifest comes last so it covers every file the
    earlier steps produced.

    Returns:
      0 on success, 1 when --overwrite was not given (the usage text
      and the refusal reason are printed).
    """
    if "--overwrite" not in sys.argv:
        print(__doc__)
        print("Refusing to run without --overwrite (this redefines the "
              "frozen state every test compares against).")
        return 1
    u.require_cocoa_environment()
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    if os.path.isdir(u.FROZEN_DIR):
        shutil.rmtree(u.FROZEN_DIR)
    os.makedirs(u.FROZEN_DIR)

    print("freezing ../data ...", flush=True)
    # the data copy is what lets users change ../data later without
    # touching the tests; .DS_Store (macOS Finder metadata) would only
    # pollute the manifest
    shutil.copytree(os.path.join(PROJECT_DIR, "data"),
                    os.path.join(u.FROZEN_DIR, "data"),
                    ignore=shutil.ignore_patterns(".DS_Store"))
    for cfg in u.EXAMPLES.values():
        shutil.copy2(os.path.join(PROJECT_DIR, cfg["provenance"]),
                     os.path.join(u.FROZEN_DIR, cfg["provenance"]))

    for example in u.EXAMPLES:
        freeze_example(example, stamp)

    reference = {
        "_meta": {
            "generated_utc": stamp,
            "omp_num_threads": os.environ["OMP_NUM_THREADS"],
            "chi2_tolerance": u.CHI2_TOLERANCE,
        }
    }
    for example, cfg in u.EXAMPLES.items():
        # every configuration gets an NLA reference; TATT only makes
        # sense for the exact-physics ones (the emulator entries are
        # advisory and compared at their shipped IA settings); the
        # FASTPT variant exists where the tests need its baseline
        variants = [("nla", {"tatt": False})]
        if not cfg.get("emulator"):
            variants.append(("tatt", {"tatt": True}))
        if cfg.get("fastpt_reference"):
            variants.append(("tatt_fastpt", {"tatt": True, "fastpt": True}))
        for suffix, kwargs in variants:
            key = f"{example}_{suffix}"
            t0 = time.time()
            chi2 = u.single_model_chi2(example, **kwargs)
            print(f"{key}: chi2 = {chi2:.6f}  ({time.time() - t0:.1f}s)",
                  flush=True)
            reference[key] = chi2
    for example, cfg in u.EXAMPLES.items():
        # the saved FASTPT-minus-CFASTPT difference: how much the two
        # implementations of the TATT perturbation-theory terms differ
        # at the reference point (the FASTPT tests print it)
        if cfg.get("fastpt_reference"):
            reference[f"{example}_fastpt_minus_cfastpt"] = (
                reference[f"{example}_tatt_fastpt"]
                - reference[f"{example}_tatt"])

    with open(u.REFERENCE_FILE, "w") as f:
        json.dump(reference, f, indent=2, sort_keys=True)
        f.write("\n")

    # compute_manifest returns {relative path: sha256} for every file
    # now under frozen/; writing it LAST means it covers every file
    # the steps above produced
    manifest = {
        "_comment": "SHA-256 of every file under tests/frozen/; verified by "
                    "every test before evaluating anything.",
        "files": u.compute_manifest(),
    }
    with open(u.MANIFEST_FILE, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"manifest: {len(manifest['files'])} files pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
