"""Maintainer tool: (re)create the frozen state the unit tests run on.

Running this redefines what the tests protect, so it refuses to run
without the explicit --overwrite flag. Only run it when a change to
the data vectors, n(z), covariance, examples, or likelihood defaults
is deliberate, and review the printed chi2 values before committing:
they become the new references the tests compare against.

What one run produces, all under tests/ (see cocoa_test_utils for how
the tests consume each piece):

  - frozen/data/: a copy of the current ../data folder.
  - frozen/EXAMPLE_*.yaml: snapshots of the example yaml files the
    EXAMPLES entries name as their provenance, kept for humans to diff
    (the tests never load them).
  - frozen/frozen_config_*.py: for each configuration listed in
    cocoa_test_utils.EXAMPLES, the model is built from the current
    example yaml, cobaya resolves it against the current likelihood
    defaults, and the complete resolved configuration is written back
    out as a yaml string, together with the exact evaluation point.
    Writing out every resolved option and parameter is what makes the
    tests independent of later edits to the live files. The 2x2pt
    entry starts from example2 with the likelihood block renamed; the
    EMUL2 entries carry the emulator theory stack with the network
    device forced to "cpu" (deterministic and machine-independent; the
    trained network files themselves are not copied: they live in
    external_modules/data/emultrf and are pinned by the EMULTRF keys
    in set_installation_options.sh).
  - frozen/data/tatt_lsst_y1.{modelvector,dataset}: a data vector
    generated with TATT at the fiducial point, plus a ".dataset" file
    (the descriptor: the small text file naming the data files a
    likelihood reads, one "key = filename" line each) pointing at it,
    and one copy of that descriptor per scale-cut mask
    (tatt_lsst_y1_M2.dataset ... tatt_lsst_y1_ones.dataset) for the
    --mask option of the comparison sweeps. Every TATT reference and
    test evaluates against this vector so its chi2 sits at a minimum,
    where it is stable; against the shipped NLA-based vector the TATT
    chi2 would sit on the side of a hill, responding linearly to tiny
    numerical changes.
  - frozen/reference_chi2.json: the reference chi2 values, one per
    configuration and variant (NLA for all; TATT for the exact
    configurations; TATT with python FAST-PT for example1/2, plus the
    saved FASTPT-minus-CFASTPT difference), computed from the frozen
    modules just written, exactly the way the tests will compute them.
  - manifest_sha256.json: the SHA-256 pin of every frozen file.

--overwrite deletes frozen/ first, and it does not write the frozen
baryonic-feedback vectors of test_baryons.py: those come from the
incremental --baryons mode, run after it. The incremental modes change
one part of an existing frozen state and re-pin the manifest:

  --baryons     (re)write frozen/data/baryon_<method>.{modelvector,
                dataset}, one pair per cocoa_test_utils.BARYON_METHODS
                entry;
  --tatt-masks  rewrite the per-mask TATT descriptors (text only, no
                model is evaluated).

Usage (from the Cocoa/ folder, cocoa environment active,
start_cocoa.sh sourced):

    python ./projects/lsst_y1/tests/generate_frozen_reference.py --overwrite
    python ./projects/lsst_y1/tests/generate_frozen_reference.py --baryons
"""

import json
import os
import shutil
import sys
import time

# The references must be produced under the same OpenMP thread count
# the tests enforce, and before any cobaya/cosmolike import.
os.environ["OMP_NUM_THREADS"] = "4"

# tests/ is not a package; insert(0, ...) puts it first on the import
# search path so cocoa_test_utils resolves from anywhere
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cocoa_test_utils as u

PROJECT_DIR = os.path.dirname(u.TESTS_DIR)

# Stored inside the frozen configurations as the likelihood data path.
# ROOTDIR-relative on purpose: the frozen modules stay portable across
# machines, and the tests overwrite it with the absolute path anyway.
FROZEN_DATA_RELPATH = "./projects/lsst_y1/tests/frozen/data"

# The skeleton of one generated frozen-configuration module. The yaml
# goes inside r""" so latex backslashes in parameter labels survive
# (r = raw string: backslashes are kept as typed). The backslash right
# after ''' eats the first newline, so the generated file starts at
# its docstring rather than a blank line. {point} and {yaml} are
# .format placeholders filled in freeze_example.
MODULE_TEMPLATE = '''\
"""AUTO-GENERATED by generate_frozen_reference.py --overwrite ({stamp}).

Frozen, fully expanded cobaya configuration for {example}
(source: {source} resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {point}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
{yaml}
"""
'''


def freeze_example(example, stamp):
    """Write one example's fully expanded frozen-configuration module.

    The expansion works by round trip through cobaya: build the model
    from the live example yaml (letting cobaya merge in the live
    likelihood defaults), then ask the model for its resolved
    configuration with model.info() and store that. The resolved form
    lists every option and every parameter explicitly, so the frozen
    module does not depend on any live default.

    Arguments:
      example = a key of u.EXAMPLES, e.g. "example1".
      stamp   = the UTC time string written into the module header.

    Returns:
      nothing; frozen/frozen_config_<example>.py is written.

    Raises:
      ValueError when a sampled parameter is neither overridden by the
      example's evaluate block nor given a ref center to fall back on
      (the point would be undefined at that parameter).
    """
    from cobaya.yaml import yaml_load_file, yaml_dump

    cfg = u.EXAMPLES[example]
    live = yaml_load_file(os.path.join(PROJECT_DIR, cfg["provenance"]))
    # The evaluate sampler's override block is the example's fiducial
    # point; keep it before stripping the sampler from the info.
    # dict(...) copies the block, so the pop below cannot take it
    # along; pop(key, None) removes a key without erroring when it
    # is already absent.
    override = dict(live["sampler"]["evaluate"]["override"])
    live.pop("sampler", None)
    live.pop("output", None)
    live["debug"] = 30
    live["timing"] = False
    # the 2x2pt configuration reuses example2's yaml with the
    # likelihood renamed (combo_3x2pt -> combo_2x2pt: same options,
    # same data, different probe selection inside cosmolike)
    # .get falls back to its second argument when the key is
    # absent, so most entries rename nothing
    source_name = cfg.get("source_likelihood", cfg["likelihood"])
    # pop removes the entry and hands back its value: the block
    # leaves under its old name and is reinserted under the new one
    likelihood_block = live["likelihood"].pop(source_name)
    live["likelihood"][cfg["likelihood"]] = likelihood_block
    likelihood_block["path"] = FROZEN_DATA_RELPATH
    likelihood_block["IA_model"] = 0
    if cfg.get("emulator"):
        # the emulated BAO/SN network declares device "cuda" in the
        # example; freezing "cpu" keeps the reference reproducible on
        # machines without a CUDA GPU (and torch on cpu is
        # deterministic)
        live["theory"]["emulbaosn"]["extra_args"]["device"] = "cpu"

    # make_model builds the evaluable cobaya Model; building it is
    # what forces cobaya to merge the live likelihood defaults into
    # the configuration
    model = u.make_model(live)
    # model.info() returns the configuration with every default
    # resolved: the complete likelihood option set and the complete
    # parameter list, exactly what must be frozen.
    updated = model.info()
    updated.pop("output", None)
    updated.pop("packages_path", None)
    updated["likelihood"][cfg["likelihood"]]["path"] = FROZEN_DATA_RELPATH

    # The frozen point: the example's override where given, the ref
    # center otherwise. Fallbacks are printed so the maintainer can
    # confirm each one is intended.
    point = {}
    fallback = []
    for name in model.parameterization.sampled_params():
        if name in override:
            point[name] = override[name]
        else:
            ref = updated["params"][name].get("ref")
            # a dict-valued ref describes a distribution; its center
            # "loc" is the fallback. The ternary picks loc for a
            # dict and the plain number otherwise.
            point[name] = ref["loc"] if isinstance(ref, dict) else ref
            fallback.append(name)
            if point[name] is None:
                raise ValueError(
                    f"parameter {name}: not in override and no ref")
    # a list is false when empty: the note prints only when at
    # least one parameter fell back to its ref center
    if fallback:
        print(f"{example}: point uses ref centers for {fallback}", flush=True)

    with open(os.path.join(u.FROZEN_DIR, cfg["frozen_module"]), "w") as f:
        # .format fills each {name} placeholder in the template with
        # the keyword argument of the same name. json.dumps writes
        # the point as JSON text, which doubles as a python literal
        # here; sort_keys makes regenerated modules diff cleanly.
        # yaml_dump returns the configuration as one yaml string and
        # rstrip trims its trailing newlines before the closing """.
        f.write(MODULE_TEMPLATE.format(
            stamp=stamp,
            example=example,
            source=cfg["provenance"],
            point=json.dumps(point, indent=4, sort_keys=True),
            yaml=yaml_dump(updated).rstrip("\n"),
        ))
    print(f"{example}: frozen config expanded to "
          f"{len(updated['params'])} parameters "
          f"({len(live['params'])} in the live example yaml)", flush=True)


def generate_tatt_datavector():
    """Write the TATT-generated data vector and its ".dataset" descriptor.

    The vector comes from the frozen 3x2pt (example2) configuration
    with the TATT point and datavector printing enabled: cosmolike
    writes the full-length theory vector, which the cosmic-shear and
    2x2pt masks select from, so one generated vector serves every
    exact-physics configuration. It must be generated against the
    original frozen dataset (the TATT descriptor written here does not
    exist yet; the printed theory vector does not depend on which
    data vector it is compared against).

    Returns:
      nothing; frozen/data/ gains the .modelvector and .dataset files.

    Raises:
      RuntimeError when the generated vector's length differs from
      the original data vector (a masking or probe mismatch), or when
      the original descriptor holds more than one data_file line (one
      with none fails earlier, with a TypeError from os.path.join).
    """
    from cobaya.yaml import yaml_load

    example = "example2"
    cfg = u.EXAMPLES[example]
    # the original dataset name comes from the frozen configuration
    # itself (load_frozen_info would already point at the TATT dataset)
    frozen_info = yaml_load(u._frozen_module(example).yaml_string)
    original_dataset = frozen_info["likelihood"][cfg["likelihood"]]["data_file"]

    # str.replace swaps the extension, pairing the vector's file
    # name with the descriptor's (tatt_lsst_y1.modelvector)
    vector_name = u.TATT_DATASET.replace(".dataset", ".modelvector")
    info = u.load_frozen_info(example, tatt=True)
    likelihood_block = info["likelihood"][cfg["likelihood"]]
    likelihood_block["data_file"] = original_dataset
    likelihood_block["print_datavector"] = True
    likelihood_block["print_datavector_file"] = (
        FROZEN_DATA_RELPATH + "/" + vector_name)

    print("generating the TATT data vector (example2, TATT point) ...",
          flush=True)
    model = u.make_model(info)
    point = u.build_point(model, example, tatt=True)
    u.evaluate_chi2(model, point)

    # sanity: the generated vector must have the same length as the
    # original one, or the masks would select the wrong entries
    data_dir = os.path.join(u.FROZEN_DIR, "data")
    with open(os.path.join(data_dir, vector_name)) as f:
        # sum(1 for _ in f) walks the file line by line and adds 1
        # per line: a line count that never loads the whole file
        # into memory (the with closes the file either way)
        generated_lines = sum(1 for _ in f)
    descriptor_path = os.path.join(data_dir, original_dataset)
    with open(descriptor_path) as f:
        # .read() with no size returns the whole file as one string
        descriptor = f.read()
    original_vector = None
    # splitlines() cuts the text into a list of lines, newlines
    # removed
    for line in descriptor.splitlines():
        if line.strip().startswith("data_file"):
            # split("=", 1) cuts at the first "=" only; [1] is the
            # part after the cut, and strip() drops the blanks
            # around it
            original_vector = line.split("=", 1)[1].strip()
    with open(os.path.join(data_dir, original_vector)) as f:
        # the same load-nothing line count as above
        original_lines = sum(1 for _ in f)
    if generated_lines != original_lines:
        raise RuntimeError(
            f"TATT data vector has {generated_lines} lines; the "
            f"original {original_vector} has {original_lines}")

    # the TATT dataset descriptor: the original with only the
    # data_file line replaced
    replaced = 0
    out_lines = []
    # keepends=True leaves the newline on the end of every line, so
    # joining the pieces rebuilds the file byte for byte and only
    # the retyped line differs
    for line in descriptor.splitlines(keepends=True):
        if line.strip().startswith("data_file"):
            out_lines.append(f"data_file = {vector_name}\n")
            replaced += 1
        else:
            out_lines.append(line)
    if replaced != 1:
        raise RuntimeError(
            f"{original_dataset}: expected exactly one data_file "
            f"line, found {replaced}")
    with open(os.path.join(data_dir, u.TATT_DATASET), "w") as f:
        # "".join(out_lines) glues the list into one string; each
        # piece still ends in its own newline
        f.write("".join(out_lines))
    print(f"TATT data vector: {vector_name} ({generated_lines} lines); "
          f"descriptor: {u.TATT_DATASET}", flush=True)


def generate_baryon_datavector(label):
    """Write one feedback method's frozen data vector and descriptor.

    The vector is the example1 theory prediction with the bfmt theory
    block computing this method's suppression, at the frozen fiducial
    point plus the method's cosmology override
    (u.BARYON_POINT_OVERRIDES, e.g. BACCOemu's omegab shift into its
    training box). The drift tests of test_baryons.py evaluate
    against this vector: at freeze time the chi2 is zero by
    construction, so any later chi2 above the tolerance means
    cosmolike or the theory block changed its prediction. (The
    accuracy checks of test_accuracy_baryons.py do not use these
    files: they regenerate their vector on the fly per run.) It runs
    in the generator's own process: every model here has example1's
    data-vector dimensions, so building them one after another is
    safe (see main).

    Arguments:
      label = a u.BARYON_METHODS label.

    Returns:
      nothing; frozen/data/ gains the .modelvector and .dataset files.

    Raises:
      RuntimeError when the generated vector's length differs from
      the original data vector, or when the original descriptor holds
      more than one data_file line (one with none fails earlier, with
      a TypeError from os.path.join).
    """
    from cobaya.yaml import yaml_load

    example = "example1"
    cfg = u.EXAMPLES[example]
    frozen_info = yaml_load(u._frozen_module(example).yaml_string)
    original_dataset = frozen_info["likelihood"][cfg["likelihood"]]["data_file"]

    dataset_name = u._baryon_dataset(label)
    vector_name = dataset_name.replace(".dataset", ".modelvector")
    info = u.load_frozen_info(example, tatt=False, baryon=label)
    likelihood_block = info["likelihood"][cfg["likelihood"]]
    likelihood_block["data_file"] = original_dataset
    likelihood_block["print_datavector"] = True
    likelihood_block["print_datavector_file"] = (
        FROZEN_DATA_RELPATH + "/" + vector_name)

    print(f"generating {vector_name} ({label}) ...", flush=True)
    model = u.make_model(info)
    point = dict(u.build_point(model, example, tatt=False))
    point.update(u.BARYON_POINT_OVERRIDES.get(label, {}))
    u.evaluate_chi2(model, point)

    data_dir = os.path.join(u.FROZEN_DIR, "data")
    with open(os.path.join(data_dir, vector_name)) as f:
        generated_lines = sum(1 for _ in f)
    descriptor_path = os.path.join(data_dir, original_dataset)
    with open(descriptor_path) as f:
        descriptor = f.read()
    original_vector = None
    for line in descriptor.splitlines():
        if line.strip().startswith("data_file"):
            original_vector = line.split("=", 1)[1].strip()
    with open(os.path.join(data_dir, original_vector)) as f:
        original_lines = sum(1 for _ in f)
    if generated_lines != original_lines:
        raise RuntimeError(
            f"baryon data vector has {generated_lines} lines; the "
            f"original {original_vector} has {original_lines}")

    replaced = 0
    out_lines = []
    for line in descriptor.splitlines(keepends=True):
        if line.strip().startswith("data_file"):
            out_lines.append(f"data_file = {vector_name}\n")
            replaced += 1
        else:
            out_lines.append(line)
    if replaced != 1:
        raise RuntimeError(
            f"{original_dataset}: expected exactly one data_file "
            f"line, found {replaced}")
    with open(os.path.join(data_dir, dataset_name), "w") as f:
        f.write("".join(out_lines))
    print(f"baryon data vector: {vector_name} ({generated_lines} "
          f"lines); descriptor: {dataset_name}", flush=True)


# The --mask reruns of the comparison sweeps read one frozen TATT
# dataset descriptor per scale-cut mask: identical to the base TATT
# descriptor except for its mask_file line (the entries of
# cocoa_test_utils.FASTPT_MASK_DATASETS). variant -> (base, mask).
TATT_MASK_VARIANTS = {
    "tatt_lsst_y1_M2.dataset": ("tatt_lsst_y1.dataset", "lsst_y1_M2_GGLOLAP0.05.mask"),
    "tatt_lsst_y1_M3.dataset": ("tatt_lsst_y1.dataset", "lsst_y1_M3_GGLOLAP0.05.mask"),
    "tatt_lsst_y1_M4.dataset": ("tatt_lsst_y1.dataset", "lsst_y1_M4_GGLOLAP0.05.mask"),
    "tatt_lsst_y1_M5.dataset": ("tatt_lsst_y1.dataset", "lsst_y1_M5_GGLOLAP0.05.mask"),
    "tatt_lsst_y1_M6.dataset": ("tatt_lsst_y1.dataset", "lsst_y1_M6_GGLOLAP0.05.mask"),
    "tatt_lsst_y1_ones.dataset": ("tatt_lsst_y1.dataset", "ones.mask"),
}

def generate_tatt_mask_datasets():
    """Write the per-mask TATT dataset descriptors.

    Each variant is the base TATT descriptor with only its mask_file
    line retyped: the comparison sweeps read them through the --mask
    option to evaluate the same generated vector under another
    scale-cut mask. Pure text, no model evaluations, so the variants
    regenerate in the --overwrite run and in the incremental
    --tatt-masks mode alike.

    Returns:
      nothing; frozen/data/ gains one descriptor per variant.

    Raises:
      RuntimeError when a base descriptor does not contain exactly
      one mask_file line.
    """
    data_dir = os.path.join(u.FROZEN_DIR, "data")
    for variant, (base, mask) in TATT_MASK_VARIANTS.items():
        with open(os.path.join(data_dir, base)) as f:
            descriptor = f.read()
        replaced = 0
        out_lines = []
        # keepends=True keeps the newline on every line, so joining
        # the pieces rebuilds the file byte for byte and only the
        # retyped line differs
        for line in descriptor.splitlines(keepends=True):
            if line.strip().startswith("mask_file"):
                out_lines.append(f"mask_file = {mask}\n")
                replaced += 1
            else:
                out_lines.append(line)
        if replaced != 1:
            raise RuntimeError(
                f"{base}: expected exactly one mask_file line, "
                f"found {replaced}")
        with open(os.path.join(data_dir, variant), "w") as f:
            f.write("".join(out_lines))
        print(f"TATT mask variant: {variant} (mask_file = {mask})",
              flush=True)


def main():
    """Rebuild tests/frozen/ and the manifest from the current project.

    The --overwrite steps, in order: delete and recreate frozen/; copy
    the data and the example snapshots; write one expanded
    frozen-configuration module per EXAMPLES entry; generate the TATT
    data vector and its per-mask descriptors; evaluate every reference
    chi2 from those modules (the same code path the tests use; NLA for
    every entry, TATT for the exact-physics ones, TATT with python
    FAST-PT where an entry asks for it) and the FASTPT-minus-CFASTPT
    differences; write the reference file; hash everything into the
    manifest. The manifest comes last so it covers every file the
    earlier steps produced. The flags --tatt-masks and --baryons
    select the incremental modes instead (module docstring).

    Returns:
      0 after --overwrite, 1 when no mode flag was given (the usage
      text and the refusal reason are printed), None (exit code 0)
      after an incremental mode.
    """
    # `in` scans the argument list for the literal flag
    if "--tatt-masks" in sys.argv:
        # incremental: rewrite the per-mask TATT descriptors of the
        # --mask comparison sweeps in an existing frozen state and
        # re-pin the manifest; pure text, no model evaluations
        u.require_cocoa_environment()
        generate_tatt_mask_datasets()
        manifest = {
            "_comment": "SHA-256 of every file under tests/frozen/; "
                        "verified by every test before evaluating "
                        "anything.",
            "files": u.compute_manifest(),
        }
        with open(u.MANIFEST_FILE, "w") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"manifest: {len(manifest['files'])} files pinned")
        return
    if "--baryons" in sys.argv:
        # incremental: add the per-method frozen baryon vectors of the
        # drift tests to an existing frozen state and re-pin the
        # manifest; nothing else changes. This project builds its
        # models in-process (all example1 dimensions), so no worker
        # subprocesses are needed.
        u.require_cocoa_environment()
        for label, _, _ in u.BARYON_METHODS:
            generate_baryon_datavector(label)
        manifest = {
            "_comment": "SHA-256 of every file under tests/frozen/; "
                        "verified by every test before evaluating "
                        "anything.",
            "files": u.compute_manifest(),
        }
        with open(u.MANIFEST_FILE, "w") as f:
            json.dump(manifest, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"manifest: {len(manifest['files'])} files pinned")
        return
    if "--overwrite" not in sys.argv:
        print(__doc__)
        print("Refusing to run without --overwrite (this redefines the "
              "frozen state every test compares against).")
        return 1
    u.require_cocoa_environment()
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    if os.path.isdir(u.FROZEN_DIR):
        shutil.rmtree(u.FROZEN_DIR)
    os.makedirs(u.FROZEN_DIR)

    print("freezing ../data ...", flush=True)
    # the data copy is what lets users change ../data later without
    # touching the tests; .DS_Store (macOS Finder metadata) would only
    # pollute the manifest. ignore_patterns builds the filter function
    # copytree calls in every folder; matching names are skipped.
    shutil.copytree(os.path.join(PROJECT_DIR, "data"),
                    os.path.join(u.FROZEN_DIR, "data"),
                    ignore=shutil.ignore_patterns(".DS_Store"))
    for cfg in u.EXAMPLES.values():
        shutil.copy2(os.path.join(PROJECT_DIR, cfg["provenance"]),
                     os.path.join(u.FROZEN_DIR, cfg["provenance"]))

    # iterating a dict yields its keys: each example name in turn
    for example in u.EXAMPLES:
        freeze_example(example, stamp)

    # the TATT-generated data vector must exist before the reference
    # loop below: every TATT reference evaluates against it
    generate_tatt_datavector()

    generate_tatt_mask_datasets()

    reference = {
        "_meta": {
            "generated_utc": stamp,
            "omp_num_threads": os.environ["OMP_NUM_THREADS"],
            "chi2_tolerance": u.CHI2_TOLERANCE,
        }
    }
    # .items() hands out (name, configuration) pairs, unpacked into
    # the two loop names
    for example, cfg in u.EXAMPLES.items():
        # every configuration gets an NLA reference; TATT only makes
        # sense for the exact-physics ones (the emulator entries are
        # advisory and compared at their shipped IA settings); the
        # FASTPT variant exists where the tests need its baseline
        variants = [("nla", {"tatt": False})]
        if not cfg.get("emulator"):
            variants.append(("tatt", {"tatt": True}))
        if cfg.get("fastpt_reference"):
            variants.append(("tatt_fastpt", {"tatt": True, "fastpt": True}))
        # each variant is a (suffix, keyword table) pair
        for suffix, kwargs in variants:
            key = f"{example}_{suffix}"
            t0 = time.time()
            # **kwargs spreads the table into keyword arguments:
            # tatt=..., and fastpt=... where present
            chi2 = u.single_model_chi2(example, **kwargs)
            # :.6f = fixed six decimals; :.1f = one decimal for the
            # elapsed seconds
            print(f"{key}: chi2 = {chi2:.6f}  ({time.time() - t0:.1f}s)",
                  flush=True)
            reference[key] = chi2
    for example, cfg in u.EXAMPLES.items():
        # the saved FASTPT-minus-CFASTPT difference: how much the two
        # implementations of the TATT perturbation-theory terms differ
        # at the reference point (the FASTPT tests print it)
        if cfg.get("fastpt_reference"):
            reference[f"{example}_fastpt_minus_cfastpt"] = (
                reference[f"{example}_tatt_fastpt"]
                - reference[f"{example}_tatt"])

    with open(u.REFERENCE_FILE, "w") as f:
        # json.dump writes the table as JSON text into the open
        # file; indent and sort_keys keep the result stable and
        # diffable, and the extra write adds the final newline text
        # files end with (load_reference round-trips it back)
        json.dump(reference, f, indent=2, sort_keys=True)
        f.write("\n")

    # compute_manifest returns {relative path: sha256} for every file
    # now under frozen/; writing it last means it covers every file
    # the steps above produced
    manifest = {
        "_comment": "SHA-256 of every file under tests/frozen/; verified by "
                    "every test before evaluating anything.",
        "files": u.compute_manifest(),
    }
    with open(u.MANIFEST_FILE, "w") as f:
        # the same stable JSON write as the reference file above
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"manifest: {len(manifest['files'])} files pinned")
    return 0


# __name__ is "__main__" only when this file runs directly as a
# script; sys.exit(main()) hands main's return value to the shell
# as the exit code (0 = success)
if __name__ == "__main__":
    sys.exit(main())
