"""Maintainer tool: (re)create the frozen state the unit tests run on.

For each example it builds the cobaya model from the CURRENT
EXAMPLE_EVALUATE yaml, resolves it against the CURRENT likelihood defaults
(cosmic_shear.yaml / combo_3x2pt.yaml, params_source.yaml, params_lens.yaml)
and writes the FULLY EXPANDED configuration — every option and every
parameter, defaults included — as a yaml string inside
tests/frozen/frozen_config_example{1,2}.py, together with the exact sampled
point. It also copies the CURRENT ../data folder, evaluates the four
reference chi2 values (example1/2, each with NLA and TATT), and pins every
frozen file in tests/manifest_sha256.json.

Running this REDEFINES what the tests protect: only run it when a change to
the data vectors, n(z), examples, or defaults is deliberate, and review the
printed chi2 shifts before committing. Usage (from the Cocoa/ folder, cocoa
environment active, start_cocoa.sh sourced):

    python ./projects/lsst_y1/tests/generate_frozen_reference.py --overwrite
"""

import json
import os
import shutil
import sys
import time

os.environ["OMP_NUM_THREADS"] = "2"  # references must match the test setup

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cocoa_test_utils as u

PROJECT_DIR = os.path.dirname(u.TESTS_DIR)
FROZEN_DATA_RELPATH = "./projects/lsst_y1/tests/frozen/data"

MODULE_TEMPLATE = '''\
"""AUTO-GENERATED by generate_frozen_reference.py --overwrite ({stamp}).

Frozen, fully expanded cobaya configuration for {example}
(source: {source} resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit makes
every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {point}

# Every option and every parameter written out explicitly: changing the live
# EXAMPLE_EVALUATE yaml files or the likelihood default yaml files does not
# affect this configuration
yaml_string = r"""
{yaml}
"""
'''


def freeze_example(example, stamp):
    from cobaya.yaml import yaml_load_file, yaml_dump

    cfg = u.EXAMPLES[example]
    live = yaml_load_file(os.path.join(PROJECT_DIR, cfg["provenance"]))
    override = dict(live["sampler"]["evaluate"]["override"])
    live.pop("sampler", None)
    live.pop("output", None)
    live["debug"] = 30
    live["timing"] = False
    like = live["likelihood"][cfg["likelihood"]]
    like["path"] = FROZEN_DATA_RELPATH
    like["IA_model"] = 0

    model = u.make_model(live)
    updated = model.info()  # fully resolved: options + params incl. defaults
    updated.pop("output", None)
    updated.pop("packages_path", None)
    updated["likelihood"][cfg["likelihood"]]["path"] = FROZEN_DATA_RELPATH

    point = {}
    fallback = []
    for p in model.parameterization.sampled_params():
        if p in override:
            point[p] = override[p]
        else:  # ref center declared in the resolved parameter block
            ref = updated["params"][p].get("ref")
            point[p] = ref["loc"] if isinstance(ref, dict) else ref
            fallback.append(p)
            if point[p] is None:
                raise ValueError(f"parameter {p}: not in override and no ref")
    if fallback:
        print(f"{example}: point uses ref centers for {fallback}", flush=True)

    with open(os.path.join(u.FROZEN_DIR, cfg["frozen_module"]), "w") as f:
        f.write(MODULE_TEMPLATE.format(
            stamp=stamp,
            example=example,
            source=cfg["provenance"],
            point=json.dumps(point, indent=4, sort_keys=True),
            yaml=yaml_dump(updated).rstrip("\n"),
        ))
    print(f"{example}: frozen config expanded to "
          f"{len(updated['params'])} parameters "
          f"({len(live['params'])} in the live example yaml)", flush=True)


def main():
    if "--overwrite" not in sys.argv:
        print(__doc__)
        print("Refusing to run without --overwrite (this redefines the "
              "frozen state every test compares against).")
        return 1
    u.require_cocoa_environment()
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    if os.path.isdir(u.FROZEN_DIR):
        shutil.rmtree(u.FROZEN_DIR)
    os.makedirs(u.FROZEN_DIR)

    print("freezing ../data ...", flush=True)
    shutil.copytree(os.path.join(PROJECT_DIR, "data"),
                    os.path.join(u.FROZEN_DIR, "data"))
    for cfg in u.EXAMPLES.values():
        # provenance snapshots (for humans to diff; the tests never load them)
        shutil.copy2(os.path.join(PROJECT_DIR, cfg["provenance"]),
                     os.path.join(u.FROZEN_DIR, cfg["provenance"]))

    for example in u.EXAMPLES:
        freeze_example(example, stamp)

    reference = {
        "_meta": {
            "generated_utc": stamp,
            "omp_num_threads": os.environ["OMP_NUM_THREADS"],
            "chi2_tolerance": u.CHI2_TOLERANCE,
        }
    }
    # references are computed exactly the way the tests compute them:
    # from the frozen modules written above
    for example in u.EXAMPLES:
        for tatt in (False, True):
            key = f"{example}_{'tatt' if tatt else 'nla'}"
            t0 = time.time()
            chi2 = u.single_model_chi2(example, tatt)
            print(f"{key}: chi2 = {chi2:.6f}  ({time.time() - t0:.1f}s)",
                  flush=True)
            reference[key] = chi2

    with open(u.REFERENCE_FILE, "w") as f:
        json.dump(reference, f, indent=2, sort_keys=True)
        f.write("\n")

    manifest = {
        "_comment": "SHA-256 of every file under tests/frozen/; verified by "
                    "every test before evaluating anything.",
        "files": u.compute_manifest(),
    }
    with open(u.MANIFEST_FILE, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"manifest: {len(manifest['files'])} files pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
